### ISSUE TITLE
composer] Hang on Resolving dependencies through SAT for over 22h

### ISSUE THREAD

**Issue by fadaile** [cisco/libacvp#241]
dear all
I want to request test vectors, use them to run some tests on my system and generate results. Upload these results back so that they can be validated. How do I do that?

**Comment by bfussell** [comment]
If you are referring to a non-runtime implementation, that capability is not currently available in the open source client.  Since it is open source you are welcome to enhance it to meet your needs.

Presently the flow is that the open source client co-exists with the crypto module and the vectors do not get saved anywhere or copied to another system.

You may also look around to see if there are other open source implementations available that have this capability - there are others on github.

**Comment by fadaile** [comment]
THANK YOU
