### ISSUE TITLE
RSA keyGen in Chinese Remainder Theorem

### ISSUE THREAD

**Issue by s-c-c** [cisco/libacvp#461]
https://github.com/cisco/libacvp/blob/5ae80820c77a06d146c6ebd2c663f97ff5e2df0d/src/acvp_rsa_keygen.c#L84

Why not output dmp1, dmq1, and iqmp in the Chinese Remainder Theorem?

**Comment by bfussell** [comment]
We do not support crt in our crypto module. Items not required for our module's validation are low priority, not because we don't want a fully functional ACV library but because we have to properly use our resources to meet the needs of our product teams.

This library is open source and can be customized to meet your needs.  We have open sourced it so the community could leverage it and benefit.  We also made it open source so the community could add features and contribute them back.

Regards,

Barry
