### ISSUE TITLE
Question Regarding --manual_registration Option

### ISSUE THREAD

**Issue by dmchodnicki** [cisco/libacvp#470]
What is the correct syntax for using the --manual_registration option?  

A ./app/acvp_app --manual_registration AES_Reg.txt command results in the following: 
***ACVP [ERR][acvp_set_json_filename:1560]--> The session must be request only to use a manual registration
Failed to set json file within ACVP ctx (rv=6).

I thought request only may have meant that a POST or GET command was needed, but 
a ./app/acvp_app --post --manual_registration AES_Reg.txt results in the following:
***ACVP [STATUS][acvp_login:2476]--> Logging in...
***ACVP [STATUS][acvp_login:2496]--> Login successful
***ACVP [ERR][acvp_post_data:3026]--> JSON val parse error.

I don't believe my registration file is the issue since it has worked previously on the NIST Demo env.

**Comment by abkarcher** [comment]
acvp_app --manual_registration <registration_file> --vector_req <save_location_file>

Currently, manual registration can only be used to download vector sets, not run them. This is because libacvp keeps track of registered capabilities internally, and we currently do not have code in place to read the registration string and register those capabilities inside the library.

We do have an internal story to track adding that functionality eventually though. Right now --manual_registration is just more of a debugging tool.

**Comment by dmchodnicki** [comment]
Andrew, thanks for the quick response.  Makes sense.  I just wanted to make sure it wasn't user error on my part.  Since you already have an internal story on this subject, I'll Close this item along with my comment.
