### ISSUE TITLE
RSA SigVer 

### ISSUE THREAD

**Issue by mtdownz** [cisco/libacvp#485]
I wanted to flag this before it becomes an issue. RSA supports multiple revisions of the FIPS-186. At the moment libacvp seems to default to "1.0" within the "Revision" tag. This seems to work okay for now and returns FIPS 186-4 vectors. The documentation posted here:
https://usnistgov.github.io/ACVP/draft-celi-acvp-rsa.html#FIPS186-2
Section 5 indicates that "1.0" should not be used within the "Revision" tag for SigVer. With FIPS 186-5 about to be final then the "Revision" tag could become quite critical with your implementation.
Thanks!

**Comment by abkarcher** [comment]
Thank you for the heads up! I will be looking into this (and am making sure we better track features we don't currently support in general).

Thanks,
Andrew

**Comment by Kritner** [comment]
Yeah FWIW this will be a (small) breaking change to clients as we're renaming a few RSA related algo/mode/revisions to better reflect the FIPS document they come from.  With FIPS186-5 coming shortly, it seems to make sense to be more explicit, rather than "1.0" which could mean 186-4 or 186-2 depending on the algo/mode, we'll be eliminating the 1.0 revision and going with the standard name instead.

https://github.com/usnistgov/ACVP/issues/990 related

**Comment by abkarcher** [comment]
Thank you @Kritner for the information. Might you have an ETA or a ballpark for when this change will be live on servers?

Thanks,
Andrew

**Comment by Kritner** [comment]
FYI the current plan is to get this changed rolled out to demo today

https://github.com/usnistgov/ACVP/issues/990#issuecomment-690396982

**Comment by Kritner** [comment]
This change is now deployed to our demo environment

**Comment by abkarcher** [comment]
Libacvp is now updated to reference FIPS186-4 instead of 1.0 for RSA.
