### ISSUE TITLE
"KAT dispatch error" on RSA sigVer response request

### ISSUE THREAD

**Issue by davyrouillard** [cisco/libacvp#498]
Hi,
I try to get vectors and the corresponding responses for a RSA sigVer algorithm.
Downloading the vectors works correctly but the command used to obtain the responses fails:

```

$ ./app/acvp_app --rsa --vector_req ./rsa_sigver_2048_SHA256_req.json --vector_rsp ./rsa_sigver_2048_SHA256_rsp.json

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/mozzila_tKAT dispatch errorrust_anchors.pem
    ACV_CERT_FILE:  certs/acvp_serma_demo.cer
    ACV_KEY_FILE:   certs/clefs_rsa.key

***ACVP [STATUS][acvp_run_vectors_from_file:867]--> Beginning offline processing of vector sets...
***ACVP [STATUS][acvp_dispatch_vector_set:2684]--> Processing vector set: 334131
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Algorithm: RSA
***ACVP [ERR][acvp_rsa_sig_kat_handler_internal:447]--> ERROR: crypto module failed the operation
***ACVP [ERR][acvp_run_vectors_from_file:955]--> KAT dispatch error

```
This kind of error has already be discussed in other posts (issues [401](https://github.com/cisco/libacvp/issues/401)) and that seems to be linked to the "non-runtime" notion (discussed in issue [340](https://github.com/cisco/libacvp/issues/340)) that I do not well understand.
My question is the following : the tests for sigver include all the required information to verify the signature (n, e, message, signature). No intermediate parameters or randomness have  therefore  to be exposed to produce the responses.
Have you any insight on why this error shows up?

Thanks,
Davy

**Comment by bfussell** [comment]
With the openssl from 1.0.2 the RSA tests utilized APIs that were not available in openssl, they were only accessible via the FOM and therefore only tested offline, not at runtime. I'm sure the app_rsa.c code could be modified to run verifies using the openssl APIs, but that wouldn't be testing the FOM implementation which was the basis for this app code. 

As we look forward to openssl 3.0.0 and the crpyto provider model I'm certain the app code will have to do exactly that since we won't be dependent on a FOM.

Regards,
Barry

**Comment by IlayGussarsky** [comment]
Hi, I've been getting the same error. As I am not familiar with FOM, can you please explain what it is and how I can fix the error?

Thanks a lot

**Comment by abkarcher** [comment]
More info about openSSL fom can be found here -
https://www.openssl.org/docs/fips.html

Our RSA processing code is designed to test the RSA crypto code within openSSL FOM for the purposes of achieving FIPS algorithm validation. There are multiple algorithms (ECDSA, DSA, RSA, and more) that are not able to be tested in runtime mode (that is, a live, functioning crypto module) because to perform these tests, the the libacvp application needs access to functions that are not exposed for use as an API.

that is why to run these, we required linkage to a FOM (--with-fom-dir at configure time). When this is done, acvp_app links directly to the FIPS object module that can be baked into OpenSSL, and the functions can be accessed for the purpose of testing without exposing dangerous APIs to end users in an active crypto library.

It is possible you can modify the app code to access openSSL APIs for some of these algs like RSA. However, it would not be testing a FIPS module and thus that sort of testing is outside the scope we were looking to achieve for our application.

I hope this helps,
Andrew
