### ISSUE TITLE
Error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Swapnay** [cisco/libacvp#526]
HI,
I am using libacvp in offline mode.Disabled kdf.
```
./configure --with-ssl-dir=/usr/include/openssl --with-libcurl-dir=/usr/local/ --with-fom_dir=/opt/chef/embedded/ --disable-kdf  

./app/acvp_app --verbose --sha-256 --vector_req /121903-Sample/361648-SHA-256/testvector-request.json --vector_rsp /121903-Sample/361648-SHA-256/actualres.json
/libacvp/app/.libs/lt-acvp_app: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

```

**Comment by abkarcher** [comment]
Hello,
The error would indicate that the linker cannot find the libssl.so that was used to build in the default search directories. Does libssl.so exist somewhere within the `include` folder you listed as the install directory? that is unusual in my experience.

Either way, setting LD_LIBRARY_PATH to include the directory your libssl.so file is in should resolve the issue. 

If you are building on a different machine than you are running on for offline mode, you would likely want to use `--enable-static --enable-offline` in your configure line so libraries would be statically linked into the application. Otherwise you want to make sure the build and target machines are linking to the exact same versions of SSL/etc.

Thanks,
Andrew

**Comment by Swapnay** [comment]
Thanks Andrew adding --enable-static --enable-offline seems to help.
