### ISSUE TITLE
How to configure for ios

### ISSUE THREAD

**Issue by harrywangca** [cisco/libacvp#539]
I am trying to run ACVP test on iPhone. But it's pretty tricky to configure the compiler for libacvp.

I am doing this with failures:

./configure --host=iphoneos CFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk" --enable-static --enable-offline

Does anyone know the right way? Many thanks

Harry

**Comment by abkarcher** [comment]
Hello,

Our CFLAGS include "-mios-version-min=[val]"  and our host is "arm-apple-darwin" instead of iphoneos. The build completes successfully but we are not currently able to test on target. Our experience with using libacvp on iOS is rather limited so far.

Please let us know if this doesn't work for you! 
Thanks,
Andrew

**Comment by harrywangca** [comment]
The compiling is perfect. I ran my tests on a iPhone 6, most of them are good. 

Thank you again.
