### ISSUE TITLE
Cisco Parser with BoringSSL?

### ISSUE THREAD

**Issue by upadhyaym** [cisco/libacvp#552]
Hi,
Can we use this parser to test BoringSSL? If yes, is there a documentation where we can get more information?

**Comment by bfussell** [comment]
Sure, however I'm pretty certain there would be some significant code changes in the app code since BoringSSL and OpenSSL have diverged quite a bit. We have not tried to build or test BoringSSL.

**Comment by abkarcher** [comment]
Hello,

Most of our documentation is in acvp.h though looking at the acvp_app implementation is likely the easiest way to gain an understanding of how it is used (I plan to improve the documentation but it is a very low priority at the moment).

If there are any other questions regarding this, please feel free to ask, otherwise I will close this issue. Thanks!

Andrew
