### ISSUE TITLE
KAS-FFC-SCC: SP 800-56A rev 3 compatibility?

### ISSUE THREAD

**Issue by janimalin** [cisco/libacvp#553]
Hi,

I'm trying to test KAS-FFC-SSC dhEphem using libacvp. I would assume that the testing would go according to this spec: https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ffc-sp800-56ar3.txt

Looking at the code it seems that libacvp does not quite implement that (but more likely rev2) ? For example domainParameterGenerationMode is missing completely etc. Parse fails for request which should be rev3 compatible.

Is my understanding correct or am I lost here somehow and running it wrong? Is there any work already ongoing to support this or should I look at adding it? Completely understandable that it's not possible to have resources for everything, but would just like to avoid duplicating work.

**Comment by bfussell** [comment]
We support a subset of the SP800-56Ar3 spec defined by the registration below(prerequistes not included). Both SP800-56Ar2 and SP800-56Ar3 registrations are in app_main.c. At present we do not check the domainParaterGenerationMode in the received vector set because only FB and FC are supported and they both operate identically.


"algorithm": "KAS-FFC-SSC",
  "revision": "Sp800-56Ar3",
  "scheme": { "dhEphem": {
                        "kasRole": [ "initiator",  "responder" ]
                       "domainParameterGenerationMethods": [  "FB",   "FC"  ],
                      "hashFunctionZ": "SHA2-512"

**Comment by abkarcher** [comment]
Hello,

Are there any other questions regarding this issue, or can it be closed? We always plan to support as many features as possible in the library but given our resources some things tend to be lower priority (and we always welcome PRs).

Thanks,
Andrew

**Comment by janimalin** [comment]
Hi,

It's clear and can be closed. I got it working for my part. I might be able to provide PR later if I get more time to put into it.

Thanks,
--Jani
