### ISSUE TITLE
KDF app support

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [cisco/libacvp#604]
Hello,

Is there any plan to add KDF app support for ssh, tls, snmp and ikev2 ?  if so when we can expect ?

Thanks,
Nag

**Comment by bfussell** [comment]
There is no schedule for KDF app support mainly because neither openssl 1.1.1 or openssl 1.0.2 support those.
We will likely put together a schedule once 3.0.0 nears official release. If you have an implementation of those KDFs then
the app code shouldn't be extremely difficult to write since your apps have to write to those APIs as well.
