### ISSUE TITLE
How to verify RSA (keyGen mode) offline testing results with ACVP test server?

### ISSUE THREAD

**Issue by ValeriyKuznetsov-Ivanti** [cisco/libacvp#626]
Hello,

I am using acvp_app for offline algorithms testing of OpenSSL 1.0.2s, FIPS 2.0.16 on Android device (aarch64). Also I have online-ready version of acvp_app on my Mac.

For some reason --all_algs or specifically --rsa are not provide me with test vectors for RSA, keyGen mode. But the Lab has requested the test results for this algorithm as well.

Is there a way (different from --all_algs or --rsa) to request test vectors for RSA (keyGen) algorithm from the ACVP test server? Is test server able to verify the test results?

I have found some test vectors for RSA (keyGen) algorithm and acvp_app built for offline testing produced json file with the test results. So, my second question - is there a way to verify these results with help of ACVP test server by running online-ready version of acvp_app application on Mac?

I hope you can help me. Thank you.

Valeriy Kuznetsov, software engineer, Ivanti.

[rsa_keygen_test_vectors.json.txt](https://github.com/cisco/libacvp/files/6660307/rsa_keygen_test_vectors.json.txt)

**Comment by bfussell** [comment]
In app_main.c function enable_rsa() you'll see that requesting RSA keygen vectors is commented out because openssl FOM 2.X does not support 186-4 keygen.  You can modify that code so the keygen vectors will get requested, however you will then need to write a handler for it in app_rsa.c function app_rsa_keygen_handler() and the 186-4 compliant RSA keygen code in FOM 2.X.

**Comment by ValeriyKuznetsov-Ivanti** [comment]
Thanks a lot.

**Comment by ValeriyKuznetsov-Ivanti** [comment]
Thank you!
