### ISSUE TITLE
Issue with AES-XTS

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#705]
I had used libacvp to run tests for AES-XTS a few months back and now I find that the tests report the following error when I try to run them.  I understand there could be a change on the NIST server that could be causing this.  Can you please tell me what I need to do to overcome this issue and run AES-XTS? 

***ACVP [INFO][log_network_status:1468]--> POST Registration...
        Status: 400
        Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
        Resp: Recieved

***ACVP [ERR][log_network_status:1491]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1492]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map ACVP-AES-XTS-1.0 - index 9 to an internal algorithm id."
    ]
  }

Regards,
Sathya.

**Comment by locksmithone** [comment]
ACVP-AES-XTS-1.0 is no longer supported, this may be the origin of the
error. Use XTS-2.0 by setting  dataUnitLenMatchesPayload to false, and
other related options.

**Comment by abkarcher** [comment]
Hello,

Unless you require the dataunitlen options, you should not need to add them at all. This is a feature for people whose AES-XTS implementations support working with smaller sections of the total payload in the test case at a time. If you do need those features, you'd have to update the client; but since you imply that your testing process has not changed, I do not think it applies to you.

Either way, the 2.0 string change I mentioned is a workaround and I would recommend updating the client when it becomes feasible.

Thanks,
Andrew

**Comment by abkarcher** [comment]
Hello,

I hope you have been able to get this working; otherwise, please let us know if you need any further assistance with this issue! I'll otherwise close it in a few days. 

Thanks,
Andrew

**Comment by nssathyan** [comment]
Hi @abkarcher !  Thank you for your inputs.  I tried the 2.0 string change, but ended up having to pick many changes in other related files.  So I currently am trying to pull the latest from github.  You can close this issue.  I shall get back to you once I have some update.

Regards,
Sathya.

**Comment by abkarcher** [comment]
Apologies the string change didn't work, I got a bit ahead of myself it seems 🙂 The latest should get you up and running.

Thanks,
Andrew

**Comment by nssathyan** [comment]
I was able to run AES XTS after getting the changes from cisco/libacvp. 

Thanks,
Sathya.
