### ISSUE TITLE
Msg should not be output in SHA MCT tests

### ISSUE THREAD

**Issue by pablodelara** [cisco/libacvp#713]
Hi,

According to latest NIST documentation, message should not be output in SHA MCT responses (which is happening now due to line 149 of src/acvp_hash.c):
https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#name-test-vector-responses

I saw that the requirement to output msg was removed in the following PR:
latest https://github.com/usnistgov/ACVP/pull/627

Should this be removed then?

Thanks,
Pablo

**Comment by abkarcher** [comment]
Hi Pablo,

At initial glance, it does look like you are correct. Fortunately this should not impact any client testing since it seems the server just ignores the included value now.

I will do some double checking when I get a chance and make sure its safe to remove for the next release. 

Thanks!
Andrew

**Comment by abkarcher** [comment]
resolved with #714 and #715. Thanks!
I expect to release new version with this fix on Monday morning (also includes KDA fix).
