### ISSUE TITLE
Can't compile libacvp 2.0

### ISSUE THREAD

**Issue by pablodelara** [cisco/libacvp#795]
When compiling the latest version of the library, I get the following error at configuration:

./configure --disable-app --enable-offline
....

checking for openssl/opensslv.h... yes
configure: error: in `/opt/libacvp':
configure: error: --with-fom-dir should not be provided with versions of SSL greater than 1.1.1

But I am not using --with-fom-dir in the configure command line.

**Comment by abkarcher** [comment]
Hello,

This seems to be a small bug that occurs when using the --disable-app functionality. You might be able to work around it by also using the "--disable-lib-check" option, but that may cause other build problems building depending on the environment.

Short of that, for now it may be best to just build the app and remove it if it is unneeded. I will have this fixed in the next release. Thanks for the find!

Andrew

**Comment by pablodelara** [comment]
Many thanks for your quick response! It worked perfectly.

**Comment by abkarcher** [comment]
Bug has been fixed in #808 and fix will be released in 2.1.0. Closing!

Thanks,
Andrew
