### ISSUE TITLE
Permission error on ./configure

### ISSUE THREAD

**Issue by waynethorsted** [cisco/libacvp#804]
Hello,
I previously installed libacvp on a UBUNTU system and had been using it without a problem.  Unfortunately, that system had an unrecoverable error and had to be rebuilt.  When I now try to install libacvp-2.0.1 (I don't remember the previous version), I get the following error.  I do not remember anything like this happening before.  Would you please let me know what I am doing wrong?

cnexadmin@lmeng-0680:~$ cd libacvp-2.0.1/
cnexadmin@lmeng-0680:~/libacvp-2.0.1$ ./configure --with-ssl-dir=/usr/bin/openssl --with-libcurl-dir=/usr/bin/curl
-bash: ./configure: Permission denied

I don't remember needing root to install it before, but I did try sudo and got this:

cnexadmin@lmeng-0680:~/libacvp-2.0.1$ sudo ./configure --with-ssl-dir=/usr/bin/openssl --with-libcurl-dir=/usr/bin/curl
[sudo] password for cnexadmin:
sudo: ./configure: command not found

Thank you,
Wayne

**Comment by abkarcher** [comment]
Hello!

I am not able to recreate this on either of two ubuntu VMs; nor can I think of anything we could have changed that would prevent configure from running at all when invoked.

This seems like something that is caused by permissions on the ubuntu machine; I would start looking there. Configure is just a shell script after all. 

Thanks,
Andrew

**Comment by waynethorsted** [comment]
Thank you for your quick reply.  It is interesting that I've gotten the same result on 2 different Ubuntu systems.  Is there any reason that I should have to be 'root' in order to do the install?

**Comment by waynethorsted** [comment]
I found my issue.  It was operator error, as expected.
Thank you again.
